ask:
  fields:
    prompt:
      required: true
      selector:
        text:
          multiline: true
    model:
      required: true
      default: sonar
      selector:
        select:
          options:
            - sonar
            - sonar-pro
            - sonar-reasoning
            - sonar-reasoning-pro
            - sonar-deep-research
          translation_key: model_options
          mode: dropdown
    enable_websearch:
      required: true
      default: false
      selector:
        boolean:
    execute_actions:
      required: true
      default: true
      selector:
        boolean:
    force_actions_execution:
      required: true
      default: false
      selector:
        boolean:
    pass_entity_context:
      required: true
      default: true
      selector:
        boolean:
    data_recency:
      required: false
      default: day
      selector:
        select:
          options:
            - day
            - week
            - month
            - year
          translation_key: data_recency_options
          mode: dropdown

